name: asp
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - huggingface_hub=0.10.1
  - numpy=1.21.5
  - python=3.8
  - pytorch=1.12.1
  - scipy=1.7.3
  - tokenizers=0.12.1
  - tqdm
  - transformers=4.23.1
  - pip:
    - truecase
    - sklearn==0.0
