name: asp
channels:
  - pytorch
  - huggingface
  - defaults
  - nvidia
dependencies:
  - pip
  - tqdm
  - numpy
  - scipy
  - python=3.8
  - pytorch
  - pytorch-cuda
  - huggingface_hub
  - transformers
  - pip:
    - truecase
    - pyhocon
    - sentencepiece
